version: 2
jobs:

  build:
    environment:
      - TZ: "/usr/share/zoneinfo/America/Los_Angeles"

    docker:
      - image: docker:18.01.0-ce-git
    working_directory: /tmp/src/
    steps:
      - run:
          name: Install parallel gzip and python3
          command: apk add --no-cache pigz python3
      - restore_cache:
          keys:
            - docker-v1-{{ .Branch }}-{{ epoch }}
            - docker-v1-{{ .Branch }}-
            - docker-v1-master-
            - docker-v1-
          paths:
            - /tmp/cache/docker.tar.gz

      - checkout
      - setup_remote_docker
      - run:
          name: Load Docker image layer cache
          no_output_timeout: 30m
          command: |
            docker info
            set +o pipefail
            if [ -f /tmp/cache/docker.tar.gz ]; then
              pigz -d --stdout /tmp/cache/docker.tar.gz | docker load
            fi
            docker images
      - run:
          name: Build Docker image
          no_output_timeout: 60m
          command: |
            # Build docker image
            e=1 && for i in {1..5}; do
              docker build \
                --cache-from=poldracklab/sdcflows \
                --rm=false \
                -t poldracklab/sdcflows:latest \
                --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
                --build-arg VCS_REF=`git rev-parse --short HEAD` \
                --build-arg VERSION="${CIRCLE_TAG:-unstable}" . \
              && e=0 && break || sleep 15
            done && [ "$e" -eq "0" ]
      - run:
          name: Docker save
          no_output_timeout: 40m
          command: |
            mkdir -p /tmp/cache
            docker save ubuntu:xenial-20161213 poldracklab/sdcflows:latest \
              | pigz -2 -p 3 > /tmp/cache/docker.tar.gz
      - persist_to_workspace:
          root: /tmp
          paths:
            - cache/docker.tar.gz

      - save_cache:
         key: docker-v1-{{ .Branch }}-{{ epoch }}
         paths:
            - /tmp/cache/docker.tar.gz

  deploy_docker:
    machine:
      image: circleci/classic:201711-01
    working_directory: /tmp/src/
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Load Docker image layer cache
          no_output_timeout: 30m
          command: |
            docker info
            set +o pipefail
            if [ -f /tmp/cache/docker.tar.gz ]; then
              sudo apt update && sudo apt -y install pigz
              pigz -d --stdout /tmp/cache/docker.tar.gz | docker load
              docker images
            fi
      - run:
          name: Deploy to Docker Hub
          no_output_timeout: 40m
          command: |
            if [[ -n "$DOCKER_PASS" ]]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push poldracklab/sdcflows:latest
              docker tag poldracklab/sdcflows poldracklab/sdcflows:$CIRCLE_TAG
              docker push poldracklab/sdcflows:$CIRCLE_TAG
            fi

  test_package:
    machine:
      image: circleci/classic:201711-01
    working_directory: /tmp/src/sdcflows
    steps:
      - checkout
      - run:
          name: Setup Python environment with virtualenvs
          command: |
            pyenv global 3.5.2
            python3 -m pip install --upgrade virtualenv
      - run:
          name: Prepare build environment
          command: |
            virtualenv --python=python3 /tmp/build
            source /tmp/build/bin/activate
            python3 -m pip install "setuptools>=30.3.0" "pip>=10.0.1" twine docutils
      - run:
          name: Prepare install environment
          command: |
            virtualenv --python=python3 /tmp/install
            source /tmp/install/bin/activate
            python3 -m pip install "setuptools>=30.3.0" "pip>=10.0.1"
      - run:
          name: Build SDCflows in build environment
          command: |
            source /tmp/build/bin/activate
            python setup.py sdist
      - store_artifacts:
          path: /tmp/src/sdcflows/dist
      - run:
          name: Check sdist package in build environment
          command: |
            source /tmp/build/bin/activate
            twine check dist/sdcflows*.tar.gz
      - run:
          name: Install sdist package into install environment and check version
          command: |
            source /tmp/install/bin/activate
            THISVERSION=$( python get_version.py )
            THISVERSION=${CIRCLE_TAG:-$THISVERSION}
            pip install dist/sdcflows*.tar.gz
            which sdcflows | grep install\\/bin
            INSTALLED_VERSION=$(sdcflows --version)
            INSTALLED_VERSION=${INSTALLED_VERSION%$'\r'}
            INSTALLED_VERSION=${INSTALLED_VERSION#*"sdcflows v"}
            echo "VERSION: \"$THISVERSION\""
            echo "INSTALLED: \"$INSTALLED_VERSION\""
            test "$INSTALLED_VERSION" = "v$THISVERSION"

  deploy_pypi:
    machine:
      image: circleci/classic:201711-01
    working_directory: /tmp/src/sdcflows
    steps:
      - checkout
      - run:
          name: Setup Python environment with virtualenvs
          command: |
            pyenv global 3.5.2
            python3 -m pip install --upgrade virtualenv
      - run:
          name: Prepare build environment
          command: |
            virtualenv --python=python3 /tmp/build
            source /tmp/build/bin/activate
            python3 -m pip install "setuptools>=30.3.0" "pip>=10.0.1" twine docutils
      - run:
          name: Prepare install environment
          command: |
            virtualenv --python=python3 /tmp/install
            source /tmp/install/bin/activate
            python3 -m pip install "setuptools>=30.3.0" "pip>=10.0.1"
      - run:
          name: Build SDCflows in build environment
          command: |
            source /tmp/build/bin/activate
            python setup.py sdist
      - store_artifacts:
          path: /tmp/src/sdcflows/dist
      - run:
          name: Check sdist package in build environment
          command: |
            source /tmp/build/bin/activate
            twine check dist/sdcflows*.tar.gz
      - run:
          name: Install sdist package into install environment and check version
          command: |
            source /tmp/install/bin/activate
            THISVERSION=$( python get_version.py )
            THISVERSION=${CIRCLE_TAG:-$THISVERSION}
            pip install dist/sdcflows*.tar.gz
            which sdcflows | grep install\\/bin
            INSTALLED_VERSION=$(sdcflows --version)
            INSTALLED_VERSION=${INSTALLED_VERSION%$'\r'}
            INSTALLED_VERSION=${INSTALLED_VERSION#*"sdcflows v"}
            echo "VERSION: \"$THISVERSION\""
            echo "INSTALLED: \"$INSTALLED_VERSION\""
            test "$INSTALLED_VERSION" = "v$THISVERSION"
      - run:
          name: Upload packages to PyPI
          command: |
            source /tmp/build/bin/activate
            twine upload dist/sdcflows*

workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test_package:
          filters:
            tags:
              only: /.*/

      - deploy_pypi:
          requires:
            - build
            - test_package
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/

      - deploy_docker:
          requires:
            - build
            - deploy_pypi
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
