name: fmriprep_docs
channels:
  - conda-forge
dependencies:
- python==3.5
- numpy>=1.11.0
- scipy=0.18.1
- scikit-learn=0.18.1
- matplotlib=2.0.0
- traits=4.6
- jinja2=2.8
- sphinx>=1.5.1
- sphinx_rtd_theme
- mock
- future
- nibabel
- statsmodels
- xvfbwrapper
- funcsigs
- networkx
- python-dateutil
- pydotplus
- cython

- pip:
    - sphinx-argparse
    - doctest-ignore-unicode
    - svgutils
    - nitime
    - nilearn
    - git+https://github.com/nipy/nipype.git@4e48d2644b19e74581904e5404569e505279835a#egg=nipype
    - git+https://github.com/poldracklab/niworkflows.git@1f6ee8fe28f85b30398e33424c8b4d0b2f20992f#egg=niworkflows
    - git+https://github.com/INCF/pybids.git@7205ae01fbdca8e8bfd26ac773b1134b84c8af0c#egg=pybids
