name: fmriprep_docs
channels:
  - conda-forge
dependencies:
- python==3.5
- numpy>=1.11.0
- scipy=0.18.1
- scikit-learn=0.18.1
- matplotlib=2.0.0
- traits=4.6
- jinja2=2.8
- sphinx>=1.5.1
- sphinx_rtd_theme
- future
- nibabel
- statsmodels
- xvfbwrapper
- funcsigs
- networkx>=2.0.0
- python-dateutil
- pydot>=1.2.3
- cython
- nipype>=1.1.6

- pip:
    - sphinx-argparse
    - doctest-ignore-unicode
    - svgutils
    - nitime
    - nilearn!=0.5.0,!=0.5.1
    - tedana>=0.0.5
    - git+https://github.com/effigies/niworkflows.git@e6a277ee5e47be5f8148b136b7201c9beb8e70a3#egg=niworkflows
    - git+https://github.com/poldracklab/smriprep.git@f1cfc37bcdc346549dbf1d037cdade3a3b32d5de#egg=smriprep
    - templateflow<0.2.0a0,>=0.1.3
