name: fmriprep_docs
channels:
  - conda-forge
dependencies:
- python==3.5
- numpy>=1.11.0
- scipy=0.18.1
- scikit-learn=0.18.1
- matplotlib=2.0.0
- traits=4.6
- jinja2=2.8
- sphinx>=1.5.1
- sphinx_rtd_theme
- mock
- future
- nibabel
- statsmodels
- xvfbwrapper
- funcsigs
- networkx>=2.0.0
- python-dateutil
- pydot>=1.2.3
- cython

- pip:
    - sphinx-argparse
    - doctest-ignore-unicode
    - svgutils
    - nitime
    - nilearn
    - git+https://github.com/poldracklab/niworkflows.git@06483c9954c003c10ff7038d931afee301a70c32#egg=niworkflows-0.3.1-dev
